Peter's flags added on request.
nuclear-multimessenger-astronomy/nmma pull request #71
Opened 2023-03-04 04:06 UTC by ritwiksharma049

I have been request to add @tsunhopang's flags by @diettim. Please check.

2023-03-04 20:47 UTC, weizmannk requested changes

2023-03-04 20:47 UTC, weizmannk commented on nmma/em/analysis.py
> +from .priors import ConditionalGaussianIotaGivenThetaCore
```suggestion
from .prior import ConditionalGaussianIotaGivenThetaCore
```

2023-03-05 05:10 UTC, ritwiksharma049 commented on nmma/em/analysis.py
> +from .priors import ConditionalGaussianIotaGivenThetaCore
corrected.

2023-03-05 07:57 UTC, weizmannk approved these changes
LGTM

2023-03-05 07:58 UTC, merged